### ISSUE TITLE
Add tool tip to “Number of Photos” element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#10]
When the user hovers over the tool tip, display a pop-up message reading: “Only the first 250 images from a gallery, photostream, or album will be imported or loaded for selection” 

Flickr Usability Report 2.1.1.5; See fig. 1 for example

**Comment by NedHenry** [comment]
3fed409da0b6c1b741e3fb0ed99dc22927a8234a
