### ISSUE TITLE
Change wording of instruction/assistive text in “Flickr URL” element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#12]
One user was confused by the example URL because Flickr has changed URL formats. Change wording from, “Paste the full url…” to “Paste the full URL of the photo, gallery, photostream, or album from Flickr”

Flickr Usability Report 2.1.1.7

**Comment by NedHenry** [comment]
Fixed in c58285f5da674632a33dea4592920f03668c9a35
