### ISSUE TITLE
When a user selects “Select Images from a single gallery, photostream or album” option from “Number of Photos” element, display images for selection immediately below the “Flickr URL” element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#13]
Once users selected the option to pick images from a gallery, etc. they expected the photos to load in their field of view. They were surprised to see the images had loaded under the “Public Visibility” form element as this element fell below the fold during our testing on a larger than average monitor. 

Flickr Usability Report 2.1.1.8; See fig. 3 for example

**Comment by NedHenry** [comment]
Fixed in c58285f5da674632a33dea4592920f03668c9a35
