### ISSUE TITLE
Remove “Create New Collection” option from “Collection” drop-down menu

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#15]
Users were unsure about what it would mean to create a new collection from within the Flickr plugin. Users felt they would first create a collection through the Collections menu option if they preferred their imported photos be in a new collection as this would allow them to assign pertinent collection metadata.

Flickr Usability Report 2.1.1.10

**Comment by NedHenry** [comment]
Fixed with 449319d5f70491a9a6e4cd85f51fbeb3cb53f348
