### ISSUE TITLE
Add “Flickr Tags” element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#17]
Users wanted the option to not import tags created by Flickr users. They preferred that tags not be imported by default. 
Add a “Flickr Tags” element above “Public Visibility” with the assistive text “Import the user-created Flickr tags associated with the imported photo(s)?” Above a single radio button. The radio button should be unchecked by default. 
Checking the button will import the Flickr tags. Leaving the button unchecked will prevent the import of Flickr tags. 

Flickr Usability Report 2.1.1.12; See fig. 4 for example.

**Comment by NedHenry** [comment]
Fixed in 4cd992524ef5426aa130096f9574e50c6541b6c0
