### ISSUE TITLE
Display a “Success” pop up message in the middle of the form

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#20]
Users stated that they did not see the current success message in the header, or only noticed it after scanning the entire page; users said that they expected the message to appear more centrally on the screen. 

Flickr Usability Report 2.2.1.2; See fig. 5 for an example of this.

**Comment by NedHenry** [comment]
Fixed in 0129372db33504cf7f4282859c11f5f4441cf8fa
