### ISSUE TITLE
Change current post-submission header message from “Your image was imported…” to “Go to Items or Collections to view imported image(s)”

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#21]
Users who are unsure where to find their imported video were more likely to re-scan the page (at which point they did see this header message). 

Flickr Usability Report 2.2.1.3; See fig. 5 for example.

**Comment by NedHenry** [comment]
Fixed in a6031dc61f140d5e3656274a714ffb2ba55deed2
