### ISSUE TITLE
“Assign No Collection” option should not group batch imported images into a “Flickr Photostream” collection

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#22]
Users who chose the “Assign No Collection” option when importing selected images from a gallery were confused when the images were collectively bundled into a new “Flickr Photostream” collection. Users preferred that these images truly be assigned no collection when they chose the “Assign No Collection” option from the drop-down menu.

Flickr Usability Report 2.2.1.4

**Comment by NedHenry** [comment]
This option had been swapped with the "Create New Collection" option. This was just fixed with bd95c7739ee0250b4ccb5fe749b8ed12a26fc28d
