### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by sssomboo** [UCSCLibrary/FlickrImport#5]
Hi,

My Flickr API is working on Omeka as I'm able to select which photos to import. It says" Flickr photoset is now being imported.." but the images never actually get imported. I go to the assigned collection, and there is nothing there. Could anyone please advise?

Thanks

**Comment by sssomboo** [comment]
Note: The Flickr API is public.

**Comment by NedHenry** [comment]
Many thanks for reporting this. I'll investigate and let you know if I can
find the problem or if I need more information from you.

All the best,
Ned Henry

**Comment by sssomboo** [comment]
Ok. Please let me know if the plugin is actually functioning on other websites so I can see if its from my part. Thanks

**Comment by NedHenry** [comment]
I have just issued a fix for this bug. The error was a result of a change to the way the Flickr API handles groups of images. I believe that I have corrected the problem, but please let me know if you continue to have problems with the latest version.

**Comment by sssomboo** [comment]
It's working now. Thank you NedHenry!
