### ISSUE TITLE
Reorder form fields so that "Number of Photos" is the first element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#6]
Users voiced the cognitive workflow for their process as, “I want to import this single image from Flickr, here is the URL…” or, “I want to choose three of the photos from this album, here is the URL…” Placing “Number of Photos” at the top better aligns with this cognitive sequence.

Flickr Usability Report 2.1.1.1

**Comment by NedHenry** [comment]
Fixed with 5006d883897f4962f9a16dc647cd700e9568c3fb
