### ISSUE TITLE
Eliminate instruction text in “Number of Photos” element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/FlickrImport#9]
Eliminate instruction text in “Number of Photos” element; currently reads “Please indicate whether….”
The new radio options are understandable without assistive text.

This is dependent on GH Issue #7 

Flickr Usability Report 2.1.1.4

**Comment by NedHenry** [comment]
Fixed in c58285f5da674632a33dea4592920f03668c9a35
